export const fonts = [
  'ABeeZee',
  'Abel',
  'Abhaya Libre',
  'Aboreto',
  'Abril Fatface',
  'Abyssinica SIL',
  'Alegreya',
  'Archivo',
  'Arial',
  'Arial Black',
  'Barlow',
  'Bebas Neue',
  'Book Antiqua',
  'Bungee',
  'Cabin',
  'Cairo',
  'Comic Sans MS',
  'Cormorant',
  'Courier',
  'Crimson Text',
  'Cursive',
  'DM Sans',
  'Encode Sans',
  'Fira Sans',
  'Francois One',
  'Garamond',
  'Georgia',
  'Gilda Display',
  'Helvetica',
  'Impact',
  'Inconsolata',
  'Inter',
  'Kanit',
  'Lato',
  'Lexend',
  'Lucida Console',
  'Lucida Sans Unicode',
  'Manrope',
  'Monaco',
  'Montserrat',
  'Noto Sans',
  'Open Sans',
  'Oswald',
  'Oxygen',
  'Pacifico',
  'Padauk',
  'Palatino Linotype',
  'Playfair Display',
  'Quattrocento',
  'Quicksand',
  'Raleway',
  'Roboto',
  'Rubik',
  'Source Sans Pro',
  'Space Mono',
  'Teko',
  'Times New Roman',
  'Trebuchet MS',
  'Ubuntu Mono',
  'Verdana',
  'Vollkorn',
  'Work Sans',
  'Yantramanav',
  'Zilla Slab',
];