export const fonts = [
  'Arial', 
  'Arial Black', 
  'Bebas Neue',  
  'Book Antiqua',
  'Cabin', 
  'Comic Sans MS', 
  'Courier', 
  'Crimson Text',  
  'Cursive', 
  'Fira Sans', 
  'Garamond', 
  'Georgia',
  'Gotham',  
  'Helvetica', 
  'Impact',
  'Inconsolata',  
  'Lato',
  'Lucida Console',  
  'Lucida Sans Unicode',
  'Monaco',
  'Montserrat', 
  'Noto Sans', 
  'Open Sans',
  'Oswald',  
  'Pacifico',
  'Palatino Linotype',
  'Playfair Display', 
  'Quicksand', 
  'Raleway', 
  'Roboto',
  'Source Sans Pro', 
  'Times New Roman',
  'Trebuchet MS',
  'Verdana',
];